package vm

import (
	"context"
	"fmt"
	"io"

	"github.com/mutms/mpd/go/internal/exec"
	"github.com/mutms/mpd/go/internal/ui"
)

// Caddy is the VM's TLS frontdoor for VM-level names, installed as an apt
// package. It is distinct from mpd-caddy.service, which terminates TLS
// for project URLs on .2; see docs/networking.md.
const (
	CaddyUnit     = "caddy.service"
	CaddyfilePath = "/etc/caddy/Caddyfile"
	// caddyDropIn runs Caddy as the dev user: the key lives under a 0700
	// dev-user directory, and the process moves rather than the key.
	// Debian's AmbientCapabilities survives the User= override, so :443
	// still binds.
	caddyDropIn = "/etc/systemd/system/caddy.service.d/mpd.conf"
)

// CaddySite is one name Caddy terminates TLS for.
type CaddySite struct {
	// Host is the public name (e.g. "150.mpd.test").
	Host string
	// Upstream is the plain-HTTP backend, host:port.
	Upstream string
}

// CaddyfileBody renders the whole Caddyfile.
//
// bindIP pins every listener to the bridge gateway, so nothing is
// published on the VM's LAN address (see docs/networking.md). auto_https
// is off because mpd's own CA signs these certificates.
func CaddyfileBody(bindIP, certPath, keyPath string, sites []CaddySite) string {
	body := "# Generated by mpd --vm-setup. Edits are overwritten.\n" +
		"{\n\tauto_https off\n}\n"
	for _, s := range sites {
		body += fmt.Sprintf(`
http://%s {
	bind %s
	redir https://{host}{uri} permanent
}

https://%s {
	bind %s
	tls %s %s
	reverse_proxy %s
}
`, s.Host, bindIP, s.Host, bindIP, certPath, keyPath, s.Upstream)
	}
	return body
}

// ConfigureCaddy writes the Caddyfile and the drop-in, then reloads.
// Idempotent: unchanged files skip both the write and the reload.
//
// certChanged must be passed in: the Caddyfile names only the cert's
// path, so a reissued certificate leaves the config byte-identical, and
// Caddy would keep serving the old leaf until restarted.
func ConfigureCaddy(ctx context.Context, out io.Writer, user, bindIP,
	certPath, keyPath string, sites []CaddySite, certChanged bool) error {

	// Restart=on-failure with no rate limit: on a cold boot Caddy can bind
	// before the gateway address exists, fail, and stay down under the
	// packaged Restart=on-abnormal. LimitNPROC=infinity: the packaged 512
	// cap counts all of the dev user's processes, a GNOME session alone
	// exceeds it, and every reload then dies with EAGAIN.
	dropIn := fmt.Sprintf("[Unit]\nStartLimitIntervalSec=0\n\n[Service]\n"+
		"User=%s\nGroup=%s\nRestart=on-failure\nRestartSec=2s\nLimitNPROC=infinity\n", user, user)
	dropInChanged, err := WriteRootOwnedFile(ctx, caddyDropIn, dropIn)
	if err != nil {
		return err
	}
	confChanged, err := WriteRootOwnedFile(ctx, CaddyfilePath,
		CaddyfileBody(bindIP, certPath, keyPath, sites))
	if err != nil {
		return err
	}

	if dropInChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"daemon-reload"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl daemon-reload failed after writing %s.", caddyDropIn)
		}
	}

	// A changed User= needs a restart; a changed Caddyfile only needs a
	// reload.
	action := "reload"
	if dropInChanged || !caddyActive(ctx) {
		action = "restart"
	}
	if confChanged || dropInChanged || certChanged || !caddyActive(ctx) {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{action, CaddyUnit}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl %s %s failed — check `journalctl -u %s`.",
				action, CaddyUnit, CaddyUnit)
		}
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"enable", CaddyUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl enable %s failed.", CaddyUnit)
	}

	for _, s := range sites {
		ui.OK(out, "https://%s/ → %s", s.Host, s.Upstream)
	}
	return nil
}

func caddyActive(ctx context.Context) bool {
	res, err := exec.Capture(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"is-active", "--quiet", CaddyUnit},
	})
	return err == nil && res.Code == 0
}
