package vm

import (
	"context"
	"fmt"
	"io"

	"github.com/mutms/mpd/go/internal/exec"
	"github.com/mutms/mpd/go/internal/ui"
)

// Caddy is the VM's TLS frontdoor: it terminates HTTPS for the names mpd
// publishes on the VM itself and reverse-proxies each to a plain-HTTP
// backend. Debian ships it in main, so this is an apt package rather than
// another container.
//
// Not to be confused with the per-runtime Caddy frontdoor sidecar, which
// terminates TLS for project URLs inside a runtime pod. Same tool, two
// levels; this one never sees project traffic.
const (
	CaddyUnit     = "caddy.service"
	CaddyfilePath = "/etc/caddy/Caddyfile"
	// caddyDropIn runs Caddy as the dev user instead of the packaged
	// `caddy` user. The certificate and key live under a 0700 dev-user
	// directory, and moving key material somewhere a second account can
	// read it is worse than moving the process. Debian's unit sets
	// AmbientCapabilities=CAP_NET_BIND_SERVICE, which survives the User=
	// override, so :443 still binds.
	caddyDropIn = "/etc/systemd/system/caddy.service.d/mpd.conf"
)

// CaddySite is one name Caddy terminates TLS for.
type CaddySite struct {
	// Host is the public name (e.g. "150.mpd.test").
	Host string
	// Upstream is the plain-HTTP backend, host:port.
	Upstream string
}

// CaddyfileBody renders the whole Caddyfile.
//
// bindIP pins every listener to one address — the podman bridge gateway,
// which the developer's laptop reaches over its static route and every
// container reaches as its gateway. Without it Caddy would also answer on
// the VM's LAN address, publishing these names to the local network,
// which is not what mpd's networking model promises.
//
// auto_https off: mpd's own CA signs these certificates, and Caddy must
// not try to obtain public ones for a .test domain it cannot validate.
func CaddyfileBody(bindIP, certPath, keyPath string, sites []CaddySite) string {
	body := "# Generated by mpd --vm-setup. Edits are overwritten.\n" +
		"{\n\tauto_https off\n}\n"
	for _, s := range sites {
		body += fmt.Sprintf(`
http://%s {
	bind %s
	redir https://{host}{uri} permanent
}

https://%s {
	bind %s
	tls %s %s
	reverse_proxy %s
}
`, s.Host, bindIP, s.Host, bindIP, certPath, keyPath, s.Upstream)
	}
	return body
}

// ConfigureCaddy writes the Caddyfile and the drop-in, then reloads.
//
// Idempotent: WriteRootOwnedFile short-circuits when content is
// unchanged, so a repeat `--vm-setup` neither rewrites nor reloads.
//
// certChanged is the one input that is not visible in the files this
// function writes. Caddy loads the certificate into memory at startup and
// the Caddyfile names only its path, so reissuing the certificate leaves
// this configuration byte-identical — and without being told, Caddy would
// go on serving the old leaf until something else happened to restart it.
// After a CA rotation that leaf is signed by a CA nothing trusts any
// more, so every name on the VM fails TLS while the config looks correct.
func ConfigureCaddy(ctx context.Context, out io.Writer, user, bindIP,
	certPath, keyPath string, sites []CaddySite, certChanged bool) error {

	// Restart=on-failure with the rate limit lifted: at boot Caddy binds the
	// podman bridge gateway, but podman only raises that address once the
	// first container attaches to the network — so on a cold boot Caddy can
	// start first, fail with "cannot assign requested address", and (under
	// the packaged unit's Restart=on-abnormal, which ignores exit-code
	// failures) stay down. Retrying every 2s until the gateway exists closes
	// that race on a VM and in a container alike; StartLimitIntervalSec=0
	// keeps systemd from giving up if the bridge takes more than a few
	// seconds.
	dropIn := fmt.Sprintf("[Unit]\nStartLimitIntervalSec=0\n\n[Service]\n"+
		"User=%s\nGroup=%s\nRestart=on-failure\nRestartSec=2s\n", user, user)
	dropInChanged, err := WriteRootOwnedFile(ctx, caddyDropIn, dropIn)
	if err != nil {
		return err
	}
	confChanged, err := WriteRootOwnedFile(ctx, CaddyfilePath,
		CaddyfileBody(bindIP, certPath, keyPath, sites))
	if err != nil {
		return err
	}

	if dropInChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"daemon-reload"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl daemon-reload failed after writing %s.", caddyDropIn)
		}
	}

	// A changed User= needs a restart; a changed Caddyfile only needs a
	// reload, which Caddy does without dropping connections.
	action := "reload"
	if dropInChanged || !caddyActive(ctx) {
		action = "restart"
	}
	if confChanged || dropInChanged || certChanged || !caddyActive(ctx) {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{action, CaddyUnit}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl %s %s failed — check `journalctl -u %s`.",
				action, CaddyUnit, CaddyUnit)
		}
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"enable", CaddyUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl enable %s failed.", CaddyUnit)
	}

	for _, s := range sites {
		ui.OK(out, "https://%s/ → %s", s.Host, s.Upstream)
	}
	return nil
}

func caddyActive(ctx context.Context) bool {
	res, err := exec.Capture(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"is-active", "--quiet", CaddyUnit},
	})
	return err == nil && res.Code == 0
}
