package vm

import (
	"context"
	"fmt"
	"io"
	gonet "net"
	"os"
	"strings"
	"time"

	"github.com/mutms/mpd/go/internal/exec"
	"github.com/mutms/mpd/go/internal/ui"
)

// dnsmasq is the VM's resolver; see docs/networking.md. It runs from
// dnsmasq-base under mpd's own unit, which names mpd's own config file,
// so the distro's /etc/dnsmasq.conf and dnsmasq.d stay the sysadmin's.
const (
	DnsmasqUnit     = "mpd-dnsmasq.service"
	dnsmasqUnitPath = "/etc/systemd/system/" + DnsmasqUnit
	dnsmasqBinary   = "/usr/sbin/dnsmasq"
)

// LLMNR answers on every address, the LAN one included; nothing here uses it.
const (
	resolvedDropInPath = "/etc/systemd/resolved.conf.d/mpd.conf"
	resolvedDropInBody = "# Managed by mpd --vm-setup. Edits are overwritten.\n[Resolve]\nLLMNR=no\n"
)

// DnsmasqConfBody renders the resolver's configuration. listenIP is the
// podman bridge gateway — the one address the laptop, the VM and every
// container all reach; iface is the bridge it sits on.
func DnsmasqConfBody(listenIP, iface string) string {
	return fmt.Sprintf(`# Generated by mpd --vm-setup. Edits are overwritten.

# Bind only the podman bridge, never the VM's LAN address: mpd's
# networking model promises nothing is published beyond the VM.
#
# bind-dynamic rather than bind-interfaces: mpdbr0 is a static bridge (a
# systemd oneshot) that is up at boot, but bind-dynamic — which watches for
# the interface and binds when it appears — stays the robust choice: it
# tolerates dnsmasq racing the bridge unit and rebinds if the bridge is ever
# recreated.
#
# The interface line is what makes that work, and it is not decoration:
# with listen-address alone dnsmasq binds nothing when the address shows
# up later, stays "active" with no listener, and every name in the zone
# fails until something restarts it.
bind-dynamic
interface=%s
listen-address=%s

# Authoritative for the whole reserved TLD, not just mpd.test: .test is
# RFC 6761 reserved and must never reach a public resolver. Unknown names
# under it get an immediate NXDOMAIN, and an AAAA query for a name with
# only an A record gets NoData — the alternative is a multi-second stall
# while a public resolver is asked about a TLD it can never answer for.
local=/test/

# Records come from /etc/hosts — dnsmasq's default, and deliberately so:
# mpd keeps its records in a managed block there, which glibc on the VM
# reads directly and this resolver serves to containers and the laptop.
# One file, no second copy. dnsmasq re-reads it on SIGHUP (systemctl
# reload), which mpd sends after every change to the block; a reload
# clears the cache without dropping in-flight queries, which a restart
# would — at glibc's full timeout per lost query.

# Upstream is the VM's own /etc/resolv.conf — again dnsmasq's default.
# Whatever manages the VM's link (dhcpcd, NetworkManager, systemd-resolved,
# a container engine) keeps that file current and dnsmasq polls it, so
# switching networks needs no restart. Forwarding to systemd-resolved's
# 127.0.0.53 stub, where the VM runs it, cannot loop: local=/test/ means a
# .test name is never forwarded at all, and nothing routes .test back here.

# Never forward a bare name or a reverse lookup for a private address to
# the upstream resolver.
domain-needed
bogus-priv
`, iface, listenIP)
}

// DnsmasqUnitBody renders the systemd unit.
//
// A system unit: it binds port 53. Restart=always: a VM without its
// resolver resolves nothing at all. ExecReload is the SIGHUP that
// re-reads /etc/hosts; see ReloadDnsmasq.
func DnsmasqUnitBody(confPath string) string {
	return `[Unit]
Description=mpd DNS resolver (dnsmasq)
Documentation=file:///opt/mpd/docs/networking.md
After=network.target mpd-bridge.service

[Service]
Type=simple
ExecStart=` + dnsmasqBinary + ` --keep-in-foreground --conf-file=` + confPath + `
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
`
}

// ConfigureDnsmasq writes the config and unit, then enables and starts
// the resolver. Idempotent: unchanged files skip the write and restart.
// Publishing records is not done here — that is the managed /etc/hosts
// block followed by ReloadDnsmasq.
func ConfigureDnsmasq(ctx context.Context, out io.Writer, listenIP, iface string) error {
	if iface == "" {
		return fmt.Errorf("Cannot configure the resolver: the podman network reports no bridge interface.")
	}

	confChanged, err := WriteRootOwnedFile(ctx, DnsmasqConfPath, DnsmasqConfBody(listenIP, iface))
	if err != nil {
		return err
	}
	unitChanged, err := WriteRootOwnedFile(ctx, dnsmasqUnitPath, DnsmasqUnitBody(DnsmasqConfPath))
	if err != nil {
		return err
	}

	if unitChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"daemon-reload"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl daemon-reload failed after writing %s.", dnsmasqUnitPath)
		}
	}
	// dnsmasq never re-reads its own config file, not even on SIGHUP, so a
	// changed config needs a restart.
	if confChanged || unitChanged || !unitIsActive(ctx, DnsmasqUnit) {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"restart", DnsmasqUnit}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl restart %s failed — check `journalctl -u %s`.",
				DnsmasqUnit, DnsmasqUnit)
		}
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"enable", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl enable %s failed.", DnsmasqUnit)
	}

	ui.OK(out, "Resolver listening on %s:53 (authoritative for .test).", listenIP)

	dropInChanged, err := WriteRootOwnedFile(ctx, resolvedDropInPath, resolvedDropInBody)
	if err != nil {
		return err
	}
	if dropInChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"try-restart", "systemd-resolved"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl try-restart systemd-resolved failed after writing %s.", resolvedDropInPath)
		}
		ui.OK(out, "LLMNR switched off in systemd-resolved.")
	}
	return nil
}

// ReloadDnsmasq makes a changed /etc/hosts live via SIGHUP. A resolver
// that is not running is left alone: setup starts it a moment later, and
// it reads the file on start.
func ReloadDnsmasq(ctx context.Context) error {
	if !unitIsActive(ctx, DnsmasqUnit) {
		return nil
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"reload", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl reload %s failed — check `journalctl -u %s`.",
			DnsmasqUnit, DnsmasqUnit)
	}
	return nil
}

// EnsureDnsmasqResolving checks the resolver actually answers, and
// restarts it once if not.
//
// "active" is not enough: dnsmasq misses an interface that appears
// between its startup scan and its netlink watch, and then stays active
// while answering nothing in the zone. A restart finds the bridge.
func EnsureDnsmasqResolving(ctx context.Context, out io.Writer, listenIP, zone string) error {
	if resolverAnswers(ctx, listenIP, zone) {
		ui.OK(out, "Resolver answers for %s at %s.", zone, listenIP)
		return nil
	}

	ui.Warn(out, "Resolver is running but not answering at %s — restarting it.", listenIP)
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"restart", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl restart %s failed — check `journalctl -u %s`.",
			DnsmasqUnit, DnsmasqUnit)
	}
	if !waitForResolver(ctx, listenIP, zone) {
		return fmt.Errorf(`The resolver is running but does not answer for %s at %s:53.

Most likely the bridge that address sits on is missing, or /etc/hosts has
no mpd block. Check with:

    ip -4 -br addr          # is there a bridge holding %s?
    sudo ss -lnup | grep :53
    grep -A30 'BEGIN mpd' /etc/hosts
    journalctl -u %s`, zone, listenIP, listenIP, DnsmasqUnit)
	}
	ui.OK(out, "Resolver answers for %s at %s.", zone, listenIP)
	return nil
}

// waitForResolver polls until the resolver answers, or gives up.
// `systemctl restart` returns before dnsmasq opens its sockets, so a
// single immediate probe reports a failure that fixes itself.
func waitForResolver(ctx context.Context, listenIP, zone string) bool {
	for i := 0; i < resolverProbeAttempts; i++ {
		if resolverAnswers(ctx, listenIP, zone) {
			return true
		}
		time.Sleep(resolverProbeInterval)
	}
	return false
}

const (
	resolverProbeInterval = 250 * time.Millisecond
	resolverProbeAttempts = 20 // 5s, generous for a local resolver restart
)

// resolverAnswers queries the resolver directly, bypassing NSS and the
// VM's resolv.conf, so the answer is about dnsmasq only.
func resolverAnswers(ctx context.Context, listenIP, name string) bool {
	r := &gonet.Resolver{
		PreferGo: true,
		Dial: func(ctx context.Context, network, _ string) (gonet.Conn, error) {
			d := gonet.Dialer{Timeout: probeTimeout}
			return d.DialContext(ctx, network, gonet.JoinHostPort(listenIP, "53"))
		},
	}
	ctx, cancel := context.WithTimeout(ctx, probeTimeout)
	defer cancel()
	addrs, err := r.LookupHost(ctx, name)
	return err == nil && len(addrs) > 0
}

// UpstreamProbeName is the name mpd forwards to prove the resolver has a
// working upstream. Debian's mirror, because it is what a container's
// first apt run asks for.
const UpstreamProbeName = "deb.debian.org"

// ForwardsUpstream reports whether the resolver answers for a name it
// must forward. Zone names come from /etc/hosts and answer even with no
// upstream at all, so this is a separate check.
func ForwardsUpstream(ctx context.Context, listenIP string) bool {
	return resolverAnswers(ctx, listenIP, UpstreamProbeName)
}

// probeTimeout keeps a wedged resolver from hanging setup.
const probeTimeout = 2 * time.Second

// resolvConfPath is the VM's own resolver list, which dnsmasq forwards
// through.
const resolvConfPath = "/etc/resolv.conf"

// RequireDNSUpstream fails when the resolver has no upstream or cannot
// forward. Two checks: an empty /etc/resolv.conf means the VM has no DNS
// at all; a populated one that does not forward is a resolver problem.
// Checked here rather than surfacing in the first apt-get.
func RequireDNSUpstream(ctx context.Context, out io.Writer, resolverIP string) error {
	servers := nameservers(resolvConfPath)
	if len(servers) == 0 {
		return fmt.Errorf(`the VM has no DNS upstream: %s lists no nameserver.

dnsmasq forwards every name outside .test to the servers in that file, so
nothing outside the zone resolves and the first apt-get will
fail. Fix the VM's own networking first (`+"`cat %s`"+`, then whatever
manages the link: dhcpcd, NetworkManager, systemd-resolved), and re-run
this command.`, resolvConfPath, resolvConfPath)
	}
	if !ForwardsUpstream(ctx, resolverIP) {
		return fmt.Errorf(`the resolver cannot forward upstream: %s does not resolve through %s.

%s lists %s, but a query forwarded there got no answer. Inspect:

    dig @%s %s
    cat %s
    journalctl -u %s | tail`,
			UpstreamProbeName, resolverIP, resolvConfPath, strings.Join(servers, ", "),
			resolverIP, UpstreamProbeName, resolvConfPath, DnsmasqUnit)
	}
	ui.OK(out, "Upstream DNS: %s.", strings.Join(servers, ", "))
	return nil
}

// nameservers reads the nameserver lines from a resolv.conf-shaped file.
// Fields, not a substring search: a commented-out line names a server too.
func nameservers(path string) []string {
	body, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var out []string
	for _, line := range strings.Split(string(body), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		out = append(out, fields[1])
	}
	return out
}
