package vm

import (
	"context"
	"fmt"
	"io"
	gonet "net"
	"os"
	"time"

	"github.com/mutms/mpd/go/internal/exec"
	"github.com/mutms/mpd/go/internal/ui"
)

// dnsmasq is the VM's resolver: one process, on the VM, answering every
// name under .test and forwarding everything else to whatever the host's
// link manager configured.
//
// It runs from Debian's dnsmasq-base package under mpd's own unit rather
// than the distro's `dnsmasq.service`. Two separate configurations of the
// same binary on one machine is a trap — the packaged unit reads
// /etc/dnsmasq.conf and /etc/dnsmasq.d/, which are the sysadmin's files,
// not mpd's — so mpd ships a unit naming its own config file and leaves
// the distro's alone.
const (
	DnsmasqUnit     = "mpd-dnsmasq.service"
	dnsmasqUnitPath = "/etc/systemd/system/" + DnsmasqUnit
	dnsmasqBinary   = "/usr/sbin/dnsmasq"
)

// DnsmasqConfBody renders the resolver's configuration.
//
// listenIP is the podman bridge gateway — the address the laptop reaches
// over its static route, the VM reaches as itself, and every container
// reaches as its gateway. One listener serves all three, which is the
// whole point of moving off a container address. iface is the bridge that
// address sits on.
func DnsmasqConfBody(listenIP, iface, hostsDir string) string {
	return fmt.Sprintf(`# Generated by mpd --vm-setup. Edits are overwritten.

# Bind only the podman bridge, never the VM's LAN address: mpd's
# networking model promises nothing is published beyond the VM.
#
# bind-dynamic rather than bind-interfaces: mpdbr0 is now a static bridge (a
# systemd oneshot) that is up at boot, but bind-dynamic — which watches for the
# interface and binds when it appears — stays the robust choice: it tolerates
# dnsmasq racing the bridge unit and rebinds if the bridge is ever recreated.
#
# The interface line is what makes that work, and it is not decoration:
# with listen-address alone dnsmasq binds nothing when the address shows
# up later, stays "active" with no listener, and every name in the zone
# fails until something restarts it.
bind-dynamic
interface=%s
listen-address=%s

# Authoritative for the whole reserved TLD, not just mpd.test: .test is
# RFC 6761 reserved and must never reach a public resolver. Unknown names
# under it get an immediate NXDOMAIN, and an AAAA query for a name with
# only an A record gets NoData — the alternative is a multi-second stall
# while a public resolver is asked about a TLD it can never answer for.
local=/test/

# mpd's records. dnsmasq watches this directory and re-reads it whenever a
# file is added, changed or removed, flushing the cache for just those
# names. That is what lets mpd create and mpd delete publish and
# retract records without signalling or restarting the resolver — a
# restart drops in-flight queries, and a lost query costs the client
# glibc's full timeout, which is ten seconds by default.
hostsdir=%s

# Not /etc/hosts: that file names the VM itself (127.0.1.1 mpd-<NNN>) and
# is no business of anything resolving through here.
no-hosts

# Upstream is systemd-resolved's view of the real per-link nameservers —
# corporate DNS on a VPN, the router on Wi-Fi — rather than the
# 127.0.0.53 stub, which resolves .test by asking this resolver and would
# therefore loop. dnsmasq watches the file, so switching networks needs no
# restart.
#
# This file also lists THIS resolver, because mpd points resolved at it
# for the .test domain. That is not a loop either: dnsmasq drops any
# upstream that is one of its own addresses, logging "ignoring nameserver
# <ip> - local interface", and forwards to the remaining per-link ones.
resolv-file=/run/systemd/resolve/resolv.conf

# Never forward a bare name or a reverse lookup for a private address to
# the upstream resolver.
domain-needed
bogus-priv
`, iface, listenIP, hostsDir)
}

// DnsmasqUnitBody renders the systemd unit.
//
// A system unit, not a user one: it binds port 53. Restart=always because
// a VM whose resolver is down resolves nothing at all — no project URL, no
// database host, no package download from inside a container.
func DnsmasqUnitBody(confPath string) string {
	return `[Unit]
Description=mpd DNS resolver (dnsmasq)
Documentation=file:///opt/mpd/docs/NETWORKING.md
After=network.target systemd-resolved.service mpd-bridge.service

[Service]
Type=simple
ExecStart=` + dnsmasqBinary + ` --keep-in-foreground --conf-file=` + confPath + `
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
`
}

// ConfigureDnsmasq writes the config and unit, then enables and starts the
// resolver. Idempotent: unchanged files short-circuit before sudo runs, so
// a repeat `--vm-setup` neither rewrites nor restarts.
//
// Note what is NOT here: publishing records. Those are hosts files under
// DNSHostsDir, which dnsmasq picks up on its own — writing one is not a
// reason to come through this function.
func ConfigureDnsmasq(ctx context.Context, out io.Writer, listenIP, iface string) error {
	if iface == "" {
		return fmt.Errorf("Cannot configure the resolver: the podman network reports no bridge interface.")
	}
	if err := os.MkdirAll(DNSHostsDir, 0o755); err != nil {
		return err
	}

	confChanged, err := WriteRootOwnedFile(ctx, DnsmasqConfPath,
		DnsmasqConfBody(listenIP, iface, DNSHostsDir))
	if err != nil {
		return err
	}
	unitChanged, err := WriteRootOwnedFile(ctx, dnsmasqUnitPath,
		DnsmasqUnitBody(DnsmasqConfPath))
	if err != nil {
		return err
	}

	if unitChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"daemon-reload"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl daemon-reload failed after writing %s.", dnsmasqUnitPath)
		}
	}
	// A changed config needs a restart: dnsmasq re-reads hostsdir and
	// resolv-file by itself, but never its own config file — not even on
	// SIGHUP.
	if confChanged || unitChanged || !unitIsActive(ctx, DnsmasqUnit) {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"restart", DnsmasqUnit}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl restart %s failed — check `journalctl -u %s`.",
				DnsmasqUnit, DnsmasqUnit)
		}
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"enable", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl enable %s failed.", DnsmasqUnit)
	}

	ui.OK(out, "Resolver listening on %s:53 (authoritative for .test).", listenIP)
	return nil
}

// EnsureDnsmasqResolving makes sure the resolver is not merely running but
// actually answering, and restarts it once if it is not.
//
// "active" is not enough, and the gap between the two is a real failure
// mode rather than a theoretical one. dnsmasq scans the interfaces once at
// startup and watches netlink for later ones; an interface appearing in
// the window between those two steps is missed permanently. Podman creates
// the bridge when the first container attaches, which on a fresh VM is
// moments after this unit starts — so the window is real, and a VM that
// loses that race comes up with a resolver that is `active`, bound to
// loopback only, and answering nothing in the zone. Every name on the VM
// fails, which reads like anything but a DNS problem.
//
// Restarting fixes it, because by now the bridge exists and the startup
// scan finds it. That is repair, not a retry loop: `--vm-setup` is the
// repair command, and this converges in one step or reports why it cannot.
//
// Call this only once something has attached to the podman network — with
// no bridge there is nothing to bind and a restart changes nothing.
func EnsureDnsmasqResolving(ctx context.Context, out io.Writer, listenIP, zone string) error {
	if resolverAnswers(ctx, listenIP, zone) {
		ui.OK(out, "Resolver answers for %s at %s.", zone, listenIP)
		return nil
	}

	ui.Warn(out, "Resolver is running but not answering at %s — restarting it.", listenIP)
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"restart", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl restart %s failed — check `journalctl -u %s`.",
			DnsmasqUnit, DnsmasqUnit)
	}
	if !waitForResolver(ctx, listenIP, zone) {
		return fmt.Errorf(`The resolver is running but does not answer for %s at %s:53.

Most likely nothing has attached to the podman network yet, so the bridge
that address sits on does not exist. Check with:

    ip -4 -br addr          # is there a bridge holding %s?
    sudo ss -lnup | grep :53
    journalctl -u %s`, zone, listenIP, listenIP, DnsmasqUnit)
	}
	ui.OK(out, "Resolver answers for %s at %s.", zone, listenIP)
	return nil
}

// waitForResolver polls until the resolver answers, or gives up.
//
// `systemctl restart` returns once the process has been spawned, not once
// dnsmasq has opened its sockets — so a single probe straight afterwards
// races the thing it is checking and reports a failure that fixes itself
// a moment later. Asked for once, this cost an hour of chasing a repair
// that had in fact worked.
func waitForResolver(ctx context.Context, listenIP, zone string) bool {
	for i := 0; i < resolverProbeAttempts; i++ {
		if resolverAnswers(ctx, listenIP, zone) {
			return true
		}
		time.Sleep(resolverProbeInterval)
	}
	return false
}

const (
	resolverProbeInterval = 250 * time.Millisecond
	resolverProbeAttempts = 20 // 5s, generous for a local resolver restart
)

// resolverAnswers asks the resolver directly, bypassing systemd-resolved
// and the VM's own resolv.conf, so the answer is about dnsmasq and not
// about how the VM is configured to reach it.
func resolverAnswers(ctx context.Context, listenIP, name string) bool {
	r := &gonet.Resolver{
		PreferGo: true,
		Dial: func(ctx context.Context, network, _ string) (gonet.Conn, error) {
			d := gonet.Dialer{Timeout: probeTimeout}
			return d.DialContext(ctx, network, gonet.JoinHostPort(listenIP, "53"))
		},
	}
	ctx, cancel := context.WithTimeout(ctx, probeTimeout)
	defer cancel()
	addrs, err := r.LookupHost(ctx, name)
	return err == nil && len(addrs) > 0
}

// probeTimeout is generous for a resolver on the same host; it exists so a
// wedged resolver cannot hang setup rather than to tune anything.
const probeTimeout = 2 * time.Second
