package vm

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/mutms/mpd/go/internal/exec"
	"github.com/mutms/mpd/go/internal/ui"
)

// dnsmasq is the VM's resolver: one process, on the VM, answering every
// name under .test and forwarding everything else to whatever the host's
// link manager configured.
//
// It runs from Debian's dnsmasq-base package under mpd's own unit rather
// than the distro's `dnsmasq.service`. Two separate configurations of the
// same binary on one machine is a trap — the packaged unit reads
// /etc/dnsmasq.conf and /etc/dnsmasq.d/, which are the sysadmin's files,
// not mpd's — so mpd ships a unit naming its own config file and leaves
// the distro's alone.
const (
	DnsmasqUnit     = "mpd-dnsmasq.service"
	dnsmasqUnitPath = "/etc/systemd/system/" + DnsmasqUnit
	dnsmasqBinary   = "/usr/sbin/dnsmasq"
)

// DnsmasqConfBody renders the resolver's configuration.
//
// listenIP is the podman bridge gateway — the address the laptop reaches
// over its static route, the VM reaches as itself, and every container
// reaches as its gateway. One listener serves all three, which is the
// whole point of moving off a container address. iface is the bridge that
// address sits on.
func DnsmasqConfBody(listenIP, iface, hostsDir string) string {
	return fmt.Sprintf(`# Generated by mpd --vm-setup. Edits are overwritten.

# Bind only the podman bridge, never the VM's LAN address: mpd's
# networking model promises nothing is published beyond the VM.
#
# bind-dynamic rather than bind-interfaces because the bridge does not
# exist until podman first attaches a container to the network, which is
# after this unit starts on a fresh VM. bind-dynamic watches for
# interfaces appearing and binds then.
#
# The interface line is what makes that work, and it is not decoration:
# with listen-address alone dnsmasq binds nothing when the address shows
# up later, stays "active" with no listener, and every name in the zone
# fails until something restarts it.
bind-dynamic
interface=%s
listen-address=%s

# Authoritative for the whole reserved TLD, not just mpd.test: .test is
# RFC 6761 reserved and must never reach a public resolver. Unknown names
# under it get an immediate NXDOMAIN, and an AAAA query for a name with
# only an A record gets NoData — the alternative is a multi-second stall
# while a public resolver is asked about a TLD it can never answer for.
local=/test/

# mpd's records. dnsmasq watches this directory and re-reads it whenever a
# file is added, changed or removed, flushing the cache for just those
# names. That is what lets mpd create and mpd delete publish and
# retract records without signalling or restarting the resolver — a
# restart drops in-flight queries, and a lost query costs the client
# glibc's full timeout, which is ten seconds by default.
hostsdir=%s

# Not /etc/hosts: that file names the VM itself (127.0.1.1 mpd-<NNN>) and
# is no business of anything resolving through here.
no-hosts

# Upstream is systemd-resolved's view of the real per-link nameservers —
# corporate DNS on a VPN, the router on Wi-Fi — rather than the
# 127.0.0.53 stub, which resolves .test by asking this resolver and would
# therefore loop. dnsmasq watches the file, so switching networks needs no
# restart.
#
# This file also lists THIS resolver, because mpd points resolved at it
# for the .test domain. That is not a loop either: dnsmasq drops any
# upstream that is one of its own addresses, logging "ignoring nameserver
# <ip> - local interface", and forwards to the remaining per-link ones.
resolv-file=/run/systemd/resolve/resolv.conf

# Never forward a bare name or a reverse lookup for a private address to
# the upstream resolver.
domain-needed
bogus-priv
`, iface, listenIP, hostsDir)
}

// DnsmasqUnitBody renders the systemd unit.
//
// A system unit, not a user one: it binds port 53. Restart=always because
// a VM whose resolver is down resolves nothing at all — no project URL, no
// database host, no package download from inside a container.
func DnsmasqUnitBody(confPath string) string {
	return `[Unit]
Description=mpd DNS resolver (dnsmasq)
Documentation=file:///opt/mpd/docs/NETWORKING.md
After=network.target systemd-resolved.service

[Service]
Type=simple
ExecStart=` + dnsmasqBinary + ` --keep-in-foreground --conf-file=` + confPath + `
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
`
}

// ConfigureDnsmasq writes the config and unit, then enables and starts the
// resolver. Idempotent: unchanged files short-circuit before sudo runs, so
// a repeat `--vm-setup` neither rewrites nor restarts.
//
// Note what is NOT here: publishing records. Those are hosts files under
// DNSHostsDir, which dnsmasq picks up on its own — writing one is not a
// reason to come through this function.
func ConfigureDnsmasq(ctx context.Context, out io.Writer, listenIP, iface string) error {
	if iface == "" {
		return fmt.Errorf("Cannot configure the resolver: the podman network reports no bridge interface.")
	}
	if err := os.MkdirAll(DNSHostsDir, 0o755); err != nil {
		return err
	}

	confChanged, err := WriteRootOwnedFile(ctx, DnsmasqConfPath,
		DnsmasqConfBody(listenIP, iface, DNSHostsDir))
	if err != nil {
		return err
	}
	unitChanged, err := WriteRootOwnedFile(ctx, dnsmasqUnitPath,
		DnsmasqUnitBody(DnsmasqConfPath))
	if err != nil {
		return err
	}

	if unitChanged {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"daemon-reload"}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl daemon-reload failed after writing %s.", dnsmasqUnitPath)
		}
	}
	// A changed config needs a restart: dnsmasq re-reads hostsdir and
	// resolv-file by itself, but never its own config file — not even on
	// SIGHUP.
	if confChanged || unitChanged || !unitIsActive(ctx, DnsmasqUnit) {
		if code, err := exec.Run(ctx, exec.Cmd{
			Name: "systemctl", Args: []string{"restart", DnsmasqUnit}, Sudo: true,
		}); err != nil || code != 0 {
			return fmt.Errorf("systemctl restart %s failed — check `journalctl -u %s`.",
				DnsmasqUnit, DnsmasqUnit)
		}
	}
	if code, err := exec.Run(ctx, exec.Cmd{
		Name: "systemctl", Args: []string{"enable", DnsmasqUnit}, Sudo: true,
	}); err != nil || code != 0 {
		return fmt.Errorf("systemctl enable %s failed.", DnsmasqUnit)
	}

	ui.OK(out, "Resolver listening on %s:53 (authoritative for .test).", listenIP)
	return nil
}
