package vm

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mutms/mpd/go/internal/ui"
)

// Markers delimiting the block mpd owns in the dev user's ~/.bashrc on the
// VM. Same contract as the ssh-config block: regenerated on every
// `mpd --vm-setup`, everything outside preserved verbatim.
const (
	promptBlockStart = "# >>> mpd vm prompt (managed by mpd --vm-setup) >>>"
	promptBlockEnd   = "# <<< mpd vm prompt <<<"
)

// EnsurePrompt appends assets/vm/prompt.bashrc to the dev user's ~/.bashrc
// so the VM's prompt reads `mpd-<NNN>-vm` — the host-side alias that
// reaches it — rather than the bare hostname, which is the alias for the
// runtime container instead.
//
// Appended at the end, not written to /etc/profile.d: a login shell reads
// /etc/profile (and its drop-ins) BEFORE ~/.bashrc, and Debian's ~/.bashrc
// assigns PS1 unconditionally, so a drop-in would be overwritten every
// time. The block has to run after that assignment, which means the tail
// of the same file.
//
// Nothing here changes a hostname; see the asset's own comment.
func EnsurePrompt(out io.Writer) error {
	source := AssetsDir + "/vm/prompt.bashrc"
	body, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("prompt asset missing: %s", source)
	}
	return ensurePrompt(out, string(body))
}

// ensurePrompt is the merge, split out so it is testable without the
// fixed /opt/mpd asset tree the VM has and a laptop checkout does not.
func ensurePrompt(out io.Writer, body string) error {
	path := filepath.Join(Home(), ".bashrc")
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("Failed to read %s: %w", path, err)
	}

	content := strings.TrimRight(stripBlock(string(existing), promptBlockStart, promptBlockEnd), "\n")
	if content != "" {
		content += "\n\n"
	}
	content += promptBlockStart + "\n" +
		"# Regenerated by `mpd --vm-setup`. Edits inside this block are lost;\n" +
		"# put your own entries outside it.\n" +
		strings.TrimRight(body, "\n") + "\n" +
		promptBlockEnd + "\n"

	if string(existing) == content {
		ui.OK(out, "VM prompt already current in ~/.bashrc.")
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("Failed to write %s: %w", path, err)
	}
	ui.OK(out, "VM prompt in ~/.bashrc (shows the -vm alias; takes effect in the next shell).")
	return nil
}
