package vm

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mutms/mpd/go/internal/ui"
)

// Markers for the block mpd owns in ~/.ssh/config. Everything between
// them is regenerated; everything outside is the developer's.
const (
	sshBlockStart = "# >>> mpd runtimes (managed by mpd --vm-setup) >>>"
	sshBlockEnd   = "# <<< mpd runtimes <<<"
)

// RuntimeHost is one runtime's SSH identity. Name composition stays with
// the caller: this package must not know the runtime's FQDN shape.
type RuntimeHost struct {
	// Patterns are the `Host` patterns: conventionally the VM-qualified
	// alias ("mpd-130-runtime"), the bare name ("runtime"), and the FQDN.
	Patterns []string
	// HostName is what ssh resolves and connects to — the FQDN dnsmasq
	// actually answers for.
	HostName string
}

// EnsureSSHConfig writes the runtime aliases into the dev user's
// ~/.ssh/config.
//
// The bare `runtime` name resolves via an /etc/hosts alias, not this
// file. Host keys are deliberately not verified: a runtime container is
// recreated freely, so its key changes routinely, and the VM is the
// trust boundary (see docs/security.md). /dev/null as known_hosts keeps
// the churn out of the developer's real file.
func EnsureSSHConfig(out io.Writer, user string, hosts []RuntimeHost) error {
	sshDir := filepath.Join(Home(), ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return err
	}
	path := filepath.Join(sshDir, "config")

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("Failed to read %s: %w", path, err)
	}

	content := strings.TrimRight(stripBlock(string(existing), sshBlockStart, sshBlockEnd), "\n")
	block := renderSSHBlock(user, hosts)
	if content != "" {
		content += "\n\n"
	}
	content += block

	if string(existing) == content {
		ui.OK(out, "Runtime SSH aliases already current in ~/.ssh/config.")
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("Failed to write %s: %w", path, err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return err
	}

	if len(hosts) == 0 {
		ui.OK(out, "No runtimes in the assets tree — wrote an empty alias block.")
		return nil
	}
	var names []string
	for _, h := range hosts {
		if len(h.Patterns) > 0 {
			names = append(names, h.Patterns[0])
		}
	}
	ui.OK(out, "SSH aliases in ~/.ssh/config: %s", strings.Join(names, ", "))
	return nil
}

// stripBlock removes a previously written managed block, leaving the
// rest of the file untouched. An unterminated block takes the remainder
// of the file with it: the alternative duplicates a start marker on
// every run.
func stripBlock(body, start, end string) string {
	var kept []string
	inBlock := false
	for _, line := range strings.Split(body, "\n") {
		switch {
		case strings.TrimSpace(line) == start:
			inBlock = true
		case inBlock && strings.TrimSpace(line) == end:
			inBlock = false
		case !inBlock:
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func renderSSHBlock(user string, hosts []RuntimeHost) string {
	var b strings.Builder
	b.WriteString(sshBlockStart + "\n")
	b.WriteString("# Regenerated by `mpd --vm-setup`. Edits inside this block are lost;\n")
	b.WriteString("# put your own entries outside it.\n")
	for _, h := range hosts {
		if h.HostName == "" || len(h.Patterns) == 0 {
			continue
		}
		b.WriteString("\nHost " + strings.Join(h.Patterns, " ") + "\n")
		b.WriteString("    HostName " + h.HostName + "\n")
		if user != "" {
			b.WriteString("    User " + user + "\n")
		}
		// See the EnsureSSHConfig comment on host keys.
		b.WriteString("    StrictHostKeyChecking no\n")
		b.WriteString("    UserKnownHostsFile /dev/null\n")
		b.WriteString("    LogLevel ERROR\n")
	}
	b.WriteString(sshBlockEnd + "\n")
	return b.String()
}
