package vm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The fixtures are real /etc/resolv.conf content from the three VM
// flavours mpd runs on: dhcpcd on a headless netinst, NetworkManager on a
// GNOME netinst, and systemd-resolved's stub on a cloud image.
func TestNameservers(t *testing.T) {
	cases := []struct {
		name string
		body string
		want []string
	}{
		{
			name: "dhcpcd: several servers, IPv6 included",
			body: "# Generated by dhcpcd from ens18.dhcp\nnameserver 8.8.8.8\nnameserver 8.8.4.4\nnameserver 2001:4860:4860::8888\n",
			want: []string{"8.8.8.8", "8.8.4.4", "2001:4860:4860::8888"},
		},
		{
			name: "resolved stub",
			body: "# This is /run/systemd/resolve/stub-resolv.conf\nnameserver 127.0.0.53\noptions edns0 trust-ad\nsearch local\n",
			want: []string{"127.0.0.53"},
		},
		{
			// The comment line names a nameserver in prose; a parser that
			// searches rather than reads fields would pick it up.
			name: "commentary is not a nameserver",
			body: "# nameserver 1.2.3.4 would be wrong\nnameserver 9.9.9.9\n",
			want: []string{"9.9.9.9"},
		},
		{
			name: "a file with no servers",
			body: "search local\n",
			want: nil,
		},
		{
			name: "a missing file is not an upstream",
			body: "",
			want: nil,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "resolv.conf")
			if tc.body != "" {
				if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			got := nameservers(path)
			if strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("nameservers = %v, want %v", got, tc.want)
			}
		})
	}
}
