<?php
// This file is created once by mpd and is yours to edit.
//
// mpd-managed settings (db credentials, dataroot, wwwroot) live in config-mpd.php.
// That file is regenerated by: mpd start <project>
// Do NOT edit config-mpd.php — your changes will be lost on the next regeneration.
// mpd keeps both files out of git via .git/info/exclude.

require_once __DIR__ . '/config-mpd.php';

// Add your custom Moodle settings below:
// $CFG->debug = DEBUG_NONE;
// $CFG->debugdisplay = 0;
// $CFG->perfdebug = 15;
// $CFG->cachetype = 'none';

require_once(__DIR__ . '/lib/setup.php'); // Do not edit
