// mpd — compile-time environment context helpers
// Single source for host/runtime path and tooling conventions.

#if !os(macOS)
import Foundation

extension Mpd.Environment {
    static var label: String {
        return "mpd-machine (Dedicated linux VM)"
    }

    static func fileFingerprint(_ path: String) -> String {
        guard FileManager.default.fileExists(atPath: path) else { return "" }

        let (rc, out) = Mpd.Environment.HostExec.capture(["sha256sum", path], suppressStderr: true)
        guard rc == 0 else { return "" }
        guard let hex = out.split(separator: " ").first, !hex.isEmpty else { return "" }
        return String(hex.prefix(16))
    }
        
    static func detectUserAndUID() -> (user: String, uid: String) {
        let user = Mpd.Environment.HostExec.capture(["whoami"], suppressStderr: true)
            .1
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let uid = Mpd.Environment.HostExec.capture(["id", "-u"], suppressStderr: true)
            .1
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return (user, uid)
    }

    /// Public keys to authorize for SSH into any mpd-managed container. Two
    /// sources, deduped:
    ///   1. `~/.ssh/authorized_keys` — keys already trusted to log in as this
    ///      user on the VM. Laptop's K_MAC lands here (that's how the user
    ///      SSHs into the VM in the first place), so `ssh -A user@vm` →
    ///      `ssh -A user@runtime` works end-to-end with K_MAC.
    ///   2. `~/.ssh/id_*.pub` — VM-local public keys. Generated by
    ///      mpd --setup if absent. Lets the user `ssh user@runtime` from
    ///      inside the VM (e.g. GNOME-desktop terminal) without -A.
    static func authorizedPublicKeys(home: String) -> [String] {
        var lines: [String] = []
        var seen = Set<String>()

        // Source 1: ~/.ssh/authorized_keys (one key per non-comment line).
        let authPath = "\(home)/.ssh/authorized_keys"
        if let content = try? String(contentsOfFile: authPath, encoding: .utf8) {
            for line in content.split(whereSeparator: { $0 == "\n" || $0 == "\r" }) {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if !trimmed.isEmpty, !trimmed.hasPrefix("#"), seen.insert(trimmed).inserted {
                    lines.append(trimmed)
                }
            }
        }

        // Source 2: ~/.ssh/id_*.pub — the VM's own keypair pubkeys.
        let sshDir = "\(home)/.ssh"
        if let entries = try? FileManager.default.contentsOfDirectory(atPath: sshDir) {
            for entry in entries.sorted() where entry.hasPrefix("id_") && entry.hasSuffix(".pub") {
                guard let pub = try? String(contentsOfFile: "\(sshDir)/\(entry)", encoding: .utf8) else { continue }
                let trimmed = pub.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty, !trimmed.hasPrefix("#"), seen.insert(trimmed).inserted {
                    lines.append(trimmed)
                }
            }
        }

        return lines
    }
}
#endif
