#!/bin/bash
# connect.sh — invoked by the .desktop launcher (Activities → "mpd-vm").
# Bring the VM up if needed, then SSH in. Auto-generated by setup.sh — the
# `Exec=` line in mpd.desktop points at this script.

START_SH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/start.sh"

# Fast liveness probe — non-interactive, no host-key prompts, short timeout.
if ! ssh -o ConnectTimeout=3 -o BatchMode=yes -o StrictHostKeyChecking=no \
        mpd-vm true 2>/dev/null; then
    if [ -x "$START_SH" ]; then
        echo "mpd-vm is not reachable — bringing the VM up..."
        echo
        bash "$START_SH" || true
        echo
    else
        echo
        echo "  Could not reach mpd-vm, and start.sh was not found at:"
        echo "    $START_SH"
        echo
        echo "  Run setup.sh in setup/linux/ to repair."
        read -r -p "  Press Enter to close..." _ || true
        exit 1
    fi
fi

ssh mpd-vm
status=$?
if [ "$status" -eq 255 ]; then
    echo
    echo "  Could not connect to mpd-vm."
    echo "  Open virt-manager and check the VM's state, or run start.sh from"
    echo "  setup/linux/ directly."
    read -r -p "  Press Enter to close..." _ || true
    exit 1
fi
