<?php
// config-mpd.php — generated by mpd. DO NOT EDIT.
// Regenerated by: mpd configure <project>
// Add custom Moodle settings to config.php (the file that includes this one).

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = '%%DBTYPE%%';
$CFG->dblibrary = 'native';
$CFG->dbhost    = '%%DBHOST%%';
$CFG->dbname    = '%%PROJECT%%';
$CFG->dbuser    = '%%PROJECT%%';
$CFG->dbpass    = '%%PROJECT%%';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array(
    'dbpersist' => 0,
);

$CFG->wwwroot  = 'https://%%PROJECT%%.mpd.test';

// Cloudflare Tunnel support: when MPD_PHP_MOODLE_CFTUNNEL=1 in this
// project's mpd.env (and MPD_UTIL_CFTUNNEL_DOMAIN is set in
// /var/lib/mpd/env/mpd-vm.env), the configure step bakes the public tunnel
// hostname here. Requests arriving with that Host get a wwwroot
// rewrite so Moodle's generated URLs match the visitor; direct
// .mpd.test access falls through unchanged. Empty string = feature
// disabled.
//
// cloudflared passes the public hostname through unchanged in HTTP_HOST
// (no rewrite happens — verified via portal diag). Caddy frontdoor
// gets the tunnel hostname added to the same vhost as the .mpd.test
// hostname (same FPM backend), so it routes correctly.
$mpdCftunnelHost = '%%CFTUNNEL_HOST%%';
if ($mpdCftunnelHost !== '' && ($_SERVER['HTTP_HOST'] ?? '') === $mpdCftunnelHost) {
    $CFG->wwwroot = 'https://' . $mpdCftunnelHost;
}

$CFG->dataroot = '/srv/data/%%PROJECT%%/dataroot';
$CFG->directorypermissions = 02777;

$CFG->sslproxy = true;

// Router (Moodle 5.0+). Caddy's php_fastcgi try_files chain ends at /r.php,
// so unknown URLs are dispatched through the router automatically. Telling
// Moodle the router is configured silences the environment check and lets
// it generate clean (no /r.php) URLs.
$CFG->routerconfigured = true;

$CFG->admin = 'admin';

$CFG->noreplyaddress = 'noreply@example.com';
$CFG->site_is_public = false;

// Note: $CFG->noemailever is intentionally NOT set. Moodle should send mail
// freely so the mailpit sidecar (configured below at localhost:1025) catches
// it. Mailpit is a black hole — messages stay inside the pod and surface in
// its web UI; nothing is forwarded to real recipients, so there's no leak
// risk to guard against. Set noemailever=true in your project's config.php
// only if you specifically want to silence Moodle's mailer entirely.

$CFG->debug = (E_ALL | 2048); // DEBUG_DEVELOPER - note that since Moodle 5.0 it is just E_ALL, but higher value here is ok.
$CFG->debugdisplay = 1;
$CFG->debug_developer_use_pretty_exceptions = 0; // Do not leak environment and source code!
$CFG->allowthemechangeonurl = 1;
$CFG->passwordpolicy = 0;
$CFG->cronclionly = 0;
$CFG->cron_keepalive = '0'; // Cron keep alive is problematic, better always avoid it.

$CFG->phpunit_dataroot  = '/srv/data/%%PROJECT%%/dataroot_phpunit';
$CFG->phpunit_prefix = 't_';

$CFG->behat_wwwroot   = 'https://behat.%%PROJECT%%.mpd.test';
$CFG->behat_dataroot  = '/srv/data/%%PROJECT%%/dataroot_behat';
$CFG->behat_prefix    = 'bht_';

// Mailpit SMTP — catches all outgoing mail. Runs as a per-runtime sidecar
// (see Mpd.Runtime.mailpitSidecarSpec) sharing the pod's netns, hence localhost.
$CFG->smtphosts = 'localhost:1025';
