<?php
// This file is created once by mpd and is yours to edit.
//
// mpd-managed settings (db credentials, dataroot, wwwroot) live in config-mpd.php.
// That file is regenerated by: mpd configure <project>
// Do NOT edit config-mpd.php — your changes will be lost on the next regeneration.
//
// Keep config-mpd.php out of git history in your project workflow (it is regenerated).

require_once __DIR__ . '/config-mpd.php';

// Add your custom Moodle settings below:
// $CFG->debug = DEBUG_NONE;
// $CFG->debugdisplay = 0;
// $CFG->perfdebug = 15;
// $CFG->cachetype = 'none';

require_once(__DIR__ . '/lib/setup.php'); // Do not edit
